// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: convert/v1/convert.proto

package convertv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/regrowag/ses/go/pkg/convert/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConvertServiceName is the fully-qualified name of the ConvertService service.
	ConvertServiceName = "convert.v1.ConvertService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConvertServiceConvertValueProcedure is the fully-qualified name of the ConvertService's
	// ConvertValue RPC.
	ConvertServiceConvertValueProcedure = "/convert.v1.ConvertService/ConvertValue"
	// ConvertServiceConvertCropYieldProcedure is the fully-qualified name of the ConvertService's
	// ConvertCropYield RPC.
	ConvertServiceConvertCropYieldProcedure = "/convert.v1.ConvertService/ConvertCropYield"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	convertServiceServiceDescriptor                = v1.File_convert_v1_convert_proto.Services().ByName("ConvertService")
	convertServiceConvertValueMethodDescriptor     = convertServiceServiceDescriptor.Methods().ByName("ConvertValue")
	convertServiceConvertCropYieldMethodDescriptor = convertServiceServiceDescriptor.Methods().ByName("ConvertCropYield")
)

// ConvertServiceClient is a client for the convert.v1.ConvertService service.
type ConvertServiceClient interface {
	// Conversion a value from one unit to another.
	ConvertValue(context.Context, *connect.Request[v1.ConvertValueRequest]) (*connect.Response[v1.ConvertValueResponse], error)
	// ConvertCropYield converts crop yields where crop-specific units are involved - eg bushels, bales
	ConvertCropYield(context.Context, *connect.Request[v1.ConvertCropYieldRequest]) (*connect.Response[v1.ConvertCropYieldResponse], error)
}

// NewConvertServiceClient constructs a client for the convert.v1.ConvertService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConvertServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConvertServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &convertServiceClient{
		convertValue: connect.NewClient[v1.ConvertValueRequest, v1.ConvertValueResponse](
			httpClient,
			baseURL+ConvertServiceConvertValueProcedure,
			connect.WithSchema(convertServiceConvertValueMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		convertCropYield: connect.NewClient[v1.ConvertCropYieldRequest, v1.ConvertCropYieldResponse](
			httpClient,
			baseURL+ConvertServiceConvertCropYieldProcedure,
			connect.WithSchema(convertServiceConvertCropYieldMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// convertServiceClient implements ConvertServiceClient.
type convertServiceClient struct {
	convertValue     *connect.Client[v1.ConvertValueRequest, v1.ConvertValueResponse]
	convertCropYield *connect.Client[v1.ConvertCropYieldRequest, v1.ConvertCropYieldResponse]
}

// ConvertValue calls convert.v1.ConvertService.ConvertValue.
func (c *convertServiceClient) ConvertValue(ctx context.Context, req *connect.Request[v1.ConvertValueRequest]) (*connect.Response[v1.ConvertValueResponse], error) {
	return c.convertValue.CallUnary(ctx, req)
}

// ConvertCropYield calls convert.v1.ConvertService.ConvertCropYield.
func (c *convertServiceClient) ConvertCropYield(ctx context.Context, req *connect.Request[v1.ConvertCropYieldRequest]) (*connect.Response[v1.ConvertCropYieldResponse], error) {
	return c.convertCropYield.CallUnary(ctx, req)
}

// ConvertServiceHandler is an implementation of the convert.v1.ConvertService service.
type ConvertServiceHandler interface {
	// Conversion a value from one unit to another.
	ConvertValue(context.Context, *connect.Request[v1.ConvertValueRequest]) (*connect.Response[v1.ConvertValueResponse], error)
	// ConvertCropYield converts crop yields where crop-specific units are involved - eg bushels, bales
	ConvertCropYield(context.Context, *connect.Request[v1.ConvertCropYieldRequest]) (*connect.Response[v1.ConvertCropYieldResponse], error)
}

// NewConvertServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConvertServiceHandler(svc ConvertServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	convertServiceConvertValueHandler := connect.NewUnaryHandler(
		ConvertServiceConvertValueProcedure,
		svc.ConvertValue,
		connect.WithSchema(convertServiceConvertValueMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	convertServiceConvertCropYieldHandler := connect.NewUnaryHandler(
		ConvertServiceConvertCropYieldProcedure,
		svc.ConvertCropYield,
		connect.WithSchema(convertServiceConvertCropYieldMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/convert.v1.ConvertService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConvertServiceConvertValueProcedure:
			convertServiceConvertValueHandler.ServeHTTP(w, r)
		case ConvertServiceConvertCropYieldProcedure:
			convertServiceConvertCropYieldHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConvertServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConvertServiceHandler struct{}

func (UnimplementedConvertServiceHandler) ConvertValue(context.Context, *connect.Request[v1.ConvertValueRequest]) (*connect.Response[v1.ConvertValueResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("convert.v1.ConvertService.ConvertValue is not implemented"))
}

func (UnimplementedConvertServiceHandler) ConvertCropYield(context.Context, *connect.Request[v1.ConvertCropYieldRequest]) (*connect.Response[v1.ConvertCropYieldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("convert.v1.ConvertService.ConvertCropYield is not implemented"))
}
